---
title: "R Notebook"
output: html_notebook
---

Functions

```{r}
pow_two <- function (x, print_info=TRUE){
  y <- x ^ 2
  if(print_info){
    print(paste(x, "to the power two equals", y))
  }
  return (y)
}

result <- pow_two(3, FALSE)
result
  

```

Function Scoping

```{r}
pow_two <- function (x){
   y <- x ^ 2
   return (y)
}

pow_two(4)
y
x
```
R passes arguments by value

```{r}
triple <- function(x){
  x <- 3*x
  x
}

a <- 5
triple(a)
a


```

Others type of parameters

```{r}
linkedin <- c(16,9,13,5,2,17,14)

interpret <- function(num_views){
  if(num_views > 15){
    print("You're popular!")
    return(num_views)
  }
  else{
    print("Try to be more visible!")
    return(0)
  }
}

interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  
  for (v in views){
    count <- count + interpret(v)
  }
  
  if(return_sum){
    return (count)
  }else{
    return (NULL)
  }
}

interpret_all(linkedin)

```

Load an R Package

```{r}

library(ggplot2)

qplot(mtcars$wt, mtcars$hp)

```


Use Apply with R

lapply

```{r}

temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

select <- function(x){
  print(mean(x))
}


list <- lapply(temp, select)
list

for (t in temp){
  
  print(min(t))
}



```


```{r}
errors<- c(1.9,-2.6,4.0,-9.5,-3.4,7.3)
print(sum(abs(round(errors))))
?round
linkedin <- list(16, 9, 13, 5, 2, 17, 14)
facebook <- list(17, 7, 5, 16, 8, 13, 14)
li_vec<-unlist(linkedin)
fb_vec<-unlist(facebook)

social_vec<-append(li_vec, fb_vec)
?append
sort(social_vec, decreasing = TRUE)
```



Regular expressions
```{r}
emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org",
            "invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")

grepl(pattern="edu", x=emails)
?grepl

hits<-grep(pattern = "edu", x=emails)
emails[hits]
```

