---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
questions<-read_csv("questions.csv")
answers<-read_csv("answers.csv")
tags<- read_csv("tags.csv")
question_tags<- read_csv("question_tags.csv")
view(questions)
view(question_tags)
view(tags)
view(answers)
```
```{r}
questions_with_tags<-questions %>%
  left_join(question_tags,by=c("id"="question_id")) %>%
  left_join(tags,by=c("id"="id"),replace_na(tag_name="only-r")) %>%
  arrange(desc(creation_date))

view(questions_with_tags)
```
```{r}
mean_score<-questions_with_tags %>%
  group_by(tag_name) %>%
  summarise(score) %>%
  arrange(desc(score))

```
```{r}
questions_answers<-questions %>%
  inner_join(answers, by=c("id"="question_id"),suffix=c("_questions","_answers")) %>%
  mutate(gap=creation_date_answers-creation_date_questions)
view(questions_answers)
```
```{r}
answer_counts<-answers%>%
  arrange(desc(question_id)) %>%
  mutate(counter=row_number())

view(answer_counts)

question_answer_counts<-questions %>%
  left_join(answer_counts, by=c("id"="question_id"), suffix=c("_questions", "_answer_counts"))

view(question_answer_counts)
```
```{r}
question_tags %>%
  inner_join(question_answer_counts, by=c("question_id"="id")) %>%
  inner_join(tags, by=c())
```

